export { default as Dashboard } from './Dashboard';
export { default as Total } from './Total';
export { default as StudentsPull } from './StudentsPull';
export { default as CoursesPull } from './CoursesPull';
export { default as Transcript } from './Transcript';
export { default as StudyTimetable } from './StudyTimetable';
export { default as ExamTimeTable } from './ExamTimeTable';
export { default as Attendance } from './Attendance';
export { default as Unbaidinvoices } from './Unbaidinvoices';
export { default as Calendar } from './Calendar';
export { default as Area } from './Charts/Area';
export { default as Bar } from './Charts/Bar';
export { default as ColorMapping } from './Charts/ColorMapping';
export { default as Financial } from './Charts/Financial';
export { default as Line } from './Charts/Line';
export { default as Pie } from './Charts/Pie';
export { default as Pyramid } from './Charts/Pyramid';
export { default as Stacked } from './Charts/Stacked';

